# Generated by Django 5.0.4 on 2024-06-06 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_ordereditems_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aded_items', to='orders.order'),
        ),
    ]
